### PR TITLE
Firefox fixes

### PR DESCRIPTION
**Pull request by TheOnlyTails**
- Fix the colors of the icons in the status column of the cloud feature showcase.
- Disable horizontal page scrolling across the site.
- Decrease the amount of contributors loaded per each row to 25.
- The favicon now changes theme with the `media` prop on `<link>` instead of with JS.
- Fix the banner image URL.
- Fix some type imports.
- Update deps. (including the changes to the `tsconfig.json`)

## Motivation and Context
The website currently uses a lot of features (especially in CSS) which Firefox doesn't support, and this PR is meant to fix those problems.

### CODE REVIEW

**Review by chingucoding — CHANGES_REQUESTED** [review]
It seems like the horizontal scroll fix did not work:
Screenshot of horizontal scroll bar visible on website

Also, it would be a lot better to figure out why there even is a horizontal scrollbar instead of just disabling horizontal scrolling

**Comment by TheOnlyTails** [comment]
I've tried looking everywhere, i still can't find it though. I'll have to take a look tomorrow.

**Comment by chingucoding** [comment]
I think this is caused by the scroller class being applied, if you remove it, it seems to work fine.

**Comment by TheOnlyTails** [comment]
That's used to add the custom scrollbar, so I'll have to take a look.

**Review by chingucoding — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@TheOnlyTails can you fix the merge conflicts?

**Review by chingucoding — DISMISSED** [review]

**Review by chingucoding — APPROVED** [review]

**Pull request merged**
