### PR TITLE
Added shortcut for collapse sidebar

### PR DESCRIPTION
**Pull request by aleksanderlukasiewicz**
## Description
Added new shortcut (Ctrl + Alt + S ) to collapse sidebar into Keyboard Shortcuts page

### CODE REVIEW

**Comment by TheOnlyTails** [comment]
Has this been merged into the app yet?

**Comment by aleksanderlukasiewicz** [comment]
> Has this been merged into the app yet?

Not yet

**Comment by yaichenbaum** [comment]
@TheOnlyTails it's being tested and should be included in the next patch.

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Pull request merged**
