### PR TITLE
Add ConEmu sample terminal profile

### PR DESCRIPTION
**Pull request by Stig124**
## Description

Add ConEmu sample terminal profile

## Motivation and Context

[ConEmu](https://conemu.github.io/) is a well-known and widely used open-source terminal replacement that supports all sorts of different terminal apps.  
Due to Files' open-source nature, I think it would be a good thing if a non-UWP open-source is 

## Screenshots (if appropriate):
N/A

### CODE REVIEW

**Comment by TheOnlyTails** [comment]
This is just the documentation for Files. Adding things to the docs won't change the actual app.
If you want this to be added, please open a PR in the Files *app* repo, not the website repo.

**Comment by Stig124** [comment]
I don't know how to code for UWP apps, the goal here is to have that on the docs, like for `CMD` and `Powershell`

**Comment by TheOnlyTails** [comment]
The purpose of the docs is to document the existing features of Files. Adding things which do not exist is misleading and defeats the purpose of having docs at all.

If you want to let users know how to add said profile to Files, that should be included in that terminal's docs, not ours.

This is not a discussion, we're not adding this.

**Comment by yaichenbaum** [comment]
@Stig124 thank you for taking the time to open this pull request, we usually expect developers to open an issue before a pull request so that we can sort out issues like this before any work is done. That being said, would you be interested in adding this profile to the documentation for ConEmu?

**Pull request closed without merging**
