### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by cinqmilleans**
## Description
This pr translates the site into French and prepares translations into other languages.

What is done:
- Creation of 2 translation files (en-US and fr-FR). The translation includes the main page, the downloads page, the popup winget and the tooltips. This does not include documentation and blog.
- It is possible to access French by prefixing the hostname with fr. (eg: https://fr.files.community/).
- There is no reference to translations on the site. It will have to be planned for later.

What can be started when this pr is integrated:
- Added many more translations. The easiest way is to provide the json english to the translators and to carry out the incorporation ourselves, to avoid them having to install the node.js tools.
- Use of translations. I advise to keep one language per prefix, but to redirect the main address if the language of the browser allows it. We will also add a manual language selector in the header or footer.

I use the typesafe-i18n library. I tested svelte-i18n, but there seems to be a conflict. Simply enabling it breaks the display of contributors and style buttons.

You have to run "pnpm run typesafe-i18n" before compiling to automatically generate typesafe classes.

We need to improve the integration, but this pr provides the basis to start involving the translators, testing the translated versions, and thinking about how to integrate the languages without modifying the current behavior for the moment.

## Motivation and Context
#40. The translation gives confidence in the software and an impression of maintenance.

## Screenshots (if appropriate):
translation

### CODE REVIEW

**Comment by yaichenbaum** [comment]
Is this how we want translations to work? I was hoping to do something similar to the app where we pull strings from a resource file.

**Comment by cinqmilleans** [comment]
@yaichenbaum To my knowledge, all translation libraries in node.js use this principle. The translations are contained in json. It is true that this is not ideal. The texts do not have statutes. A translator cannot spot a text that has changed and there is no software to manage the translations. I think this is the best Node.js can do.

One solution would be to automate the creation of these translation files. For example, having a dedicated uwp project, which contains resources, and a script that reads all the resources to create the files in the correct format. such solutions may be available. I will inquire.

**Comment by TheOnlyTails** [comment]
There's a Svelte library called svelte-i18n, so we could use it if we wanted.

**Comment by cinqmilleans** [comment]
I tried this library. But when I activate it, the localized texts work, but the other scripts no longer work (list of contributors, display of features, ...). I may have missed something.

Anyway, svelte-i18n uses json, so a system will have to be put in place to generate it from xliff to keep the texts up to date.

**Comment by TheOnlyTails** [comment]
This isn't a native app though, it's a website. We should definitely use JSON for the localization format.

**Comment by yaichenbaum** [comment]
> This isn't a native app though, it's a website. We should definitely use JSON for the localization format.

I'm fine with json

**Comment by babakfp** [comment]
Is there something like `.pot`, `.po`, `.mo` for Svelte? Using a JSON file for translations is like downgrading to ages ago, in comparison to using tools like what Wordpress uses. [You can see an example here (Poedit)](https://poedit.net). There is also [a free plugin](https://wordpress.org/plugins/loco-translate) (for Wordpress) that can automate the translation from Google Translate API!

This:
Screenshot 2022-05-25 171117

...in compare to this:
Screenshot 2022-05-25 171302

**Comment by TheOnlyTails** [comment]
This is superseded by the [`translation`](/files-community/website/tree/translation) branch I'm currently working on. You're welcome to contribute French translations there once it's merged.

**Pull request closed without merging**
