### PR TITLE
Compress images

### PR DESCRIPTION
**Pull request by AgentRBY**
## Description

I have compressed some images from the blog to make them load faster. The blog-resources folder has reduced its size by 11.16MB (19.42MB -> 8.26MB)

### CODE REVIEW

**Review by chingucoding — COMMENTED** [review]
Out of curiosity, why is the Git screenshot smaller than the previous one?

**Comment by chingucoding** [comment]
@yaira2 If you also think the images look fine, feel free to merge this PR

**Comment by yaira2** [comment]
> Out of curiosity, why is the Git screenshot smaller than the previous one?

This should probably be reverted.

**Comment by yaira2** [comment]
@AgentRBY thank you for your contribution, for the future I think it's worth noting that we use ImgBot to take care of compressing images. While it's sometimes possible to compress images further, we'd rather rely on ImgBot to ensure a balance between image quality and size.

**Pull request merged**
