### PR TITLE
Feature: Added transitions between pages

### LINKED ISSUE #532: Scroll to top after opening blog post
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Microsoft Edge

### Description

Currently if you open any of the bottom posts, the user will be at the bottom of the page, which is not good UX.

### Steps To Reproduce

_No response_

### Expected behavior

The user should be scrolled to the top after opening the blog page

### Relevant Assets

https://github.com/files-community/Website/assets/68181944/a47d3778-61a7-4f4a-aa01-c5f366530d36

### PR DESCRIPTION
**Pull request by TheOnlyTails**
## Description

Added some cool new transitions between pages and among other elements, including:
- Regular pages crossfade between each other
- When transitioning between the main blog page and individiual blog posts, the title and thumbnail of each post animate between their position in each page smoothly.
- The marker indicating the current docs page in the docs sidebar animates between selected items

Please comment if you have any ideas for what we can add; I'm so excited about this I'd love to just experiment and see what's possible.

## Motivation and Context

SvelteKit [recently added support](https://github.com/sveltejs/kit/pull/9605) for the `onNavigate` lifecycle function, which unlocked the usage of the View Transition API.
This API makes visually appealing, app-like transitions easily possible on the web, and I saw the opportunity and jumped on it.

Fixes #532 

## Screenshots (if appropriate):

https://github.com/files-community/Website/assets/65342367/79ec2c1a-1a0c-4e4a-8059-79a13e53df43

https://github.com/files-community/Website/assets/65342367/1d9682d1-c333-49c3-b741-61012ec653ee

### CODE REVIEW

**Review by yaira2 — APPROVED** [review]

**Comment by yaira2** [comment]
Was the blog page layout reversed?
image

**Comment by TheOnlyTails** [comment]
Yes, I discussed it with @mdtauk and we agreed that it makes the transition look more natural.

**Comment by chingucoding** [comment]
I think this is really cool, thanks for implementing this. Given that we now animate the page header when opening a blog page, would it be worth scrolling the top when opening a specific blog post? I know that the blog page being visible in the middle was present beforehand, however with the animation I feel like this oddity is made even worse.

**Comment by TheOnlyTails** [comment]
@chingucoding removing the `scroller` class from the `<body>` element did the trick, all pages now scroll to the top after navigating. Here's how this looks with the transitions:

https://github.com/files-community/Website/assets/65342367/ce8f6b18-b54b-458e-b3d1-fa6d91754063

**Review by yaira2 — APPROVED** [review]
LGTM

**Pull request merged**
