### PR TITLE
Docs: Added translations docs

### PR DESCRIPTION
**Pull request by 0x5bfa**

### CODE REVIEW

**Comment by yaira2** [comment]
There is usally a Cloudflare link to preview the changes.

**Comment by yaira2** [comment]
@0x5bfa can you try loading the new page? https://5724ce51.files-website-cml.pages.dev/docs/contributing/translating

**Comment by 0x5bfa** [comment]
It shows error dialog.
I don't come up with any idea...

**Comment by yaira2** [comment]
Can you try converting the images to png?

**Comment by yaira2** [comment]
@0x5bfa how did you push the commit? I think it only deploys the test version if the commit is signed.

**Comment by 0x5bfa** [comment]
Ahh sorry I did it in GitHub Codespaces since I don't have a PC rn here.

**Comment by yaira2** [comment]
@TheOnlyTails do you have any ideas why Cloudflare isn't deploying this branch?

**Pull request closed without merging**
