### PR TITLE
Docs: Add translation to docs

### PR DESCRIPTION
**Pull request by Lamparter**
Renewed version of #682

### CODE REVIEW

**Comment by Lamparter** [comment]
# 🎉
image

**Comment by yaira2** [comment]
How did you fix the issue with loading the page?

**Comment by Lamparter** [comment]
> How did you fix the issue with loading the page?

It was an error with [_this_](https://github.com/files-community/Website/pull/706/commits/aa1fa2139b0712f3de859293863957f68842d911#diff-a3dbf745bbb8c306d4c60f94315a818b0c105596ab429fe67485db6593b17631R64) line due to the curly bracket not being wrapped and the markdown parser thinking that a variable was trying to be inserted.
Also, `mdsvex` doesn't support markdown images in the format provided IIRC so they weren't rendering properly, so I changed them to HTML tags.

**Review by yaira2 — APPROVED** [review]

**Comment by yaira2** [comment]
Thank you @0x5bfa and @Lamparter.

**Comment by Lamparter** [comment]
Thanks!

**Pull request merged**
