### PR TITLE
Added automatic docs tree generation

### PR DESCRIPTION
**Pull request by TheOnlyTails**
## Description

Added automatic, on-the-fly generation of the docs tree.
This runs server-side on the edge, keeping the UX fast, while improving DX for docs editors.
Added `category.md` meta files for specifying metadata for docs categories.

refactor: replaced usages of `$page.url` with `$page.route.id`

## Motivation and Context

So far, adding a page required adding an entry in a JSON object, which was tiresome.

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@TheOnlyTails can you fix the merge conflicts?

**Comment by TheOnlyTails** [comment]
Not if we want automatic generation. It sorts alphabetically by default, but we can use any algorithm we want as it can be implemented in code.

**Review by yaira2 — DISMISSED** [review]
LGTM

**Comment by TheOnlyTails** [comment]
Took me 3 tries, but I think it's done now.

**Pull request merged**
