### PR TITLE
Added playback hotkey in media preview to keyboard shortcuts documentation

### PR DESCRIPTION
**Pull request by TomaszSteblik**
Added hotkey for media playback in keyboard shortcuts documentation to reflect my recent pull request in main Files repository.

### CODE REVIEW

**Review by chingucoding — APPROVED** [review]
Awesome, thank you for adding this feature and updating the documentation @TomaszSteblik !
@yaichenbaum Should we merge this now or wait until the feature is also available to users?

**Comment by yaichenbaum** [comment]
> Awesome, thank you for adding this feature and updating the documentation @TomaszSteblik ! @yaichenbaum Should we merge this now or wait until the feature is also available to users?

Good question, let's wait until the next release before merging this.

**Comment by chingucoding** [comment]
Then let's wait, @yaichenbaum do you happen to know approximately when this could be?

**Comment by yaichenbaum** [comment]
> Then let's wait, @yaichenbaum do you happen to know approximately when this could be?

@chingucoding between one to two months.

**Comment by yaichenbaum** [comment]
@TomaszSteblik can you resolve the conflicts?

**Comment by TomaszSteblik** [comment]
> @TomaszSteblik can you resolve the conflicts?

Of course

**Review by yaichenbaum — APPROVED** [review]

**Pull request merged**
