### PR TITLE
Added sideload package for v2.0.34

### PR DESCRIPTION
**Pull request by yaichenbaum**

### CODE REVIEW

**Comment by chingucoding** [comment]
This might be a bit late, but are we sure it is fine to host foreign DLL files on our site (namely the telemetry and Newtonsoft JSON ones) from a legal standpoint?

**Comment by yaichenbaum** [comment]
> This might be a bit late, but are we sure it is fine to host foreign DLL files on our site (namely the telemetry and Newtonsoft JSON ones) from a legal standpoint?

@chingucoding they are included in the release package from msbuild for distribution, is there a way to double check?

**Comment by chingucoding** [comment]
> @chingucoding they are included in the release package from msbuild for distribution, is there a way to double check?

If they are part of the compiled package it's fine I guess, but looking at the PR, we are actually uploading the actual DLL files which I am not sure if that is good. But if there is no other way to do this from a technical standpoint, I guess it's fine.

**Comment by yaichenbaum** [comment]
@chingucoding will it still work if I remove them?

**Comment by TheOnlyTails** [comment]
Which files need to be downloaded for it to work? Just the app installer, or the accompanying folder as well?

**Comment by TheOnlyTails** [comment]
I also want to implement an endpoint which downloads the latest installer automatically, so we won't have to update the download link.

**Comment by chingucoding** [comment]
> @chingucoding will it still work if I remove them? I think they are necessary for the installation process.

Well I deleted the DLL files inside the telemetry folder and it seemed to install just fine.

**Comment by yaichenbaum** [comment]
@chingucoding great! Can you push the changes?

**Comment by yaichenbaum** [comment]
> Which files need to be downloaded for it to work? Just the app installer, or the accompanying folder as well?

The app installer will always be in the same location, you can use this download link `ms-appinstaller:?source=http://files.community/packages/Files.Package.appinstaller`.

**Comment by chingucoding** [comment]
Well if we would have read the install script, we would have known that the folder was optional. It was only to collect usage of the install script.

**Comment by yaichenbaum** [comment]
@chingucoding is there a switch to prevent the folder from being created?

**Comment by chingucoding** [comment]
@yaichenbaum According to the script yes:
`This can be excluded at build time by setting the MSBuild property AppxLogTelemetryFromSideloadingScript to false`
Should we change this on the files project?

**Comment by yaichenbaum** [comment]
Yes, I'll add the switch.

**Review by chingucoding — APPROVED** [review]
PR looks good to me.

**Pull request merged**
