### PR TITLE
GitHub: Improved README and contributing guidelines

### PR DESCRIPTION
**Pull request by 0x5bfa**
## Description

Really simplified README.md and created CONTRIBUTING.md
Also moved some GitHub related documents to the .github folder.

## Motivation and Context

Current README was too long and took me long time to start contributing.

## Screenshots (if appropriate):

Preview: https://github.com/0x5bfa/Website/tree/5bfa/readme

### CODE REVIEW

**Comment by TheOnlyTails** [comment]
This looks fine, but the README should be kept at the top level of the repo.

**Comment by 0x5bfa** [comment]
It's not. The reason why is to simplify the root folder contents.
README still [can be viewed at the root](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#about-readmes).

**Comment by TheOnlyTails** [comment]
It's not about whether it works or not, it's about convention - people (and lots of tooling) expect the README file to be available at the top level of the repo.

**Comment by 0x5bfa** [comment]
Even if people and *a lot of* tools expect so, they just can find using GitHub feature Go To.
What tool would cause an issue for example btw?

It doesn't really matter in this pr whether readme is placed at the root or not so I can move back, though.

**Pull request closed without merging**
