### PR TITLE
Update Korean translation

### PR DESCRIPTION
**Pull request by rivercory**
## Description
Untranslated phrases have been translated into Korean!

## Motivation and Context
Users who can't speak English will have a hard time interpreting this website.

### CODE REVIEW

**Comment by 0x5bfa** [comment]
We manage translations in [Crowdin](https://crowdin.com/project/files-website), could you help us with it there?

**Comment by rivercory** [comment]
Crowdin says the Korean translation is perfect, but it's not.

**Comment by 0x5bfa** [comment]
Looks like they are [already translated](https://crowdin.com/editor/files-website/58/en-ko?view=comfortable&filter=basic&value=0#q=Remap) in [Jul 19, 2024](https://crowdin.com/project/files-website/activity-stream)

**Comment by rivercory** [comment]
However, the translation is not reflected. I reflected it in my PR, so I think it will be resolved if you merge my PR.

**Comment by 0x5bfa** [comment]
I mean we haven't fetched translated data from Crowdin to this repo yet since the last fetch.
@yaira2 does it sometimes.

**Comment by rivercory** [comment]
So when will that Crowdin translation be patched?

**Comment by yaira2** [comment]
Thanks for the reminder, I synced with Crowdin in #692.

**Pull request closed without merging**
