### PR TITLE
Added an RSS feed (`/blog/feed.rss`)

### LINKED ISSUE #228: Feature: RSS feed for blog
I would really like to follow the project releases. I use RSS because it's easy to track so I can announce them on my podcast. The Files blog does not have a feed.

If you have your releases somewhere other than github, since I don't see them on here, a feed to that would suffice also. 

Thanks for the great work, this would definitely help get the word out.

### PR DESCRIPTION
**Pull request by TheOnlyTails**
## Description

fixed the share links in blog posts (`href` doesn't work on `<MenuFlyoutItem>`)
blog metadata searching is now based on `route.id`, not `url.pathname`
updated deps

## Motivation and Context

Closes #228

### CODE REVIEW

**Review by chingucoding — CHANGES_REQUESTED** [review]
The RSS feed file is not actually a valid RSS feed according to W3C: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwebsite-git-blog-rss-feed-filescommunity.vercel.app%2Fblog%2Ffeed.rss

Also shouldn't we show somewhere that an RSS feed exists?

**Comment by TheOnlyTails** [comment]
The feed is shown in the share menu of every post.
The validity issues do need fixing though, I'll get on it tomorrow.

**Review by chingucoding — APPROVED** [review]
LGTM, thanks for working on that @TheOnlyTails !

@yaira2 Is showing the RSS feed as part of the share menu enough or should we give the options somewhere else too?

**Comment by yaira2** [comment]
I think it's enough

**Pull request merged**
